# Используем современную версию синтаксиса Docker Compose
version: '3.8'

# Определяем сервисы (контейнеры), которые будут запущены
services:
  # Сервис для базы данных PostgreSQL
  db:
    image: postgres:15 # Используем официальный образ PostgreSQL версии 15
    container_name: comet_db # Удобное имя для контейнера
    restart: always # Всегда перезапускать контейнер, если он остановился
    environment:
      POSTGRES_USER: root # Имя пользователя для подключения к БД
      POSTGRES_PASSWORD: 1337 # !!! ЗАМЕНИТЕ ЭТОТ ПАРОЛЬ НА СВОЙ !!!
      POSTGRES_DB: comet_tracker_db # Название базы данных, которая будет создана при первом запуске
    ports:
      - "5433:5432" # Пробрасываем порт 5432 с контейнера на ваш компьютер
    volumes:
      - postgres_data:/var/lib/postgresql/data # Сохраняем данные БД в именованный том, чтобы они не пропали после перезапуска

  # Сервис для Adminer - веб-интерфейса для управления БД
  adminer:
    image: adminer # Используем официальный образ Adminer
    container_name: comet_db_admin # Удобное имя для контейнера
    restart: always
    ports:
      - "8081:8080" # Пробрасываем порт 8080 с контейнера на ваш компьютер
    depends_on:
      - db # Указываем, что Adminer должен запускаться только ПОСЛЕ запуска сервиса 'db'

# Определяем именованные тома (volumes) для персистентного хранения данных
volumes:
  postgres_data: